spring.application.name=securitydemo
spring.security.user.name=admin
spring.security.user.password=12345

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test

spring.app.jwtSecret=mySecretKey123!#92786
spring.app.jwtExpirationMs=86,400,000